### ISSUE TITLE
Picasso 2.5.2 Caching not working when custom downloader is defined

### ISSUE THREAD

**Issue by ChristianLJ** [square/picasso#1185]
I can't get the disk cache to work in Picasso 2.5.2. I have the following relevant dependencies:
```
- com.squareup.picasso:picasso:2.5.2
- com.squareup.okhttp:okhttp:2.5.0
- com.squareup.okhttp:okhttp-urlconnection:2.5.0
```
In my application class i am creating an OkHttpClient(), setting the cache and the Picasso instance.
```
OkHttpClient picassoClient = new OkHttpClient();
picassoClient.interceptors().add(new OAuth2Interceptor());
File cache = CacheUtils.createDefaultCacheDir(this);
picassoClient.setCache(new com.squareup.okhttp.Cache(cache, CacheUtils.calculateDiskCacheSize(cache)));

Picasso picasso = new Picasso.Builder(this)
.defaultBitmapConfig(Bitmap.Config.RGB_565)
.indicatorsEnabled(BuildConfig.DEBUG)
.downloader(new OkHttpDownloader(picassoClient))
.build();

Picasso.setSingletonInstance(picasso);
```
My CacheUtils class:
```
public class CacheUtils {
    public static File createDefaultCacheDir(Context context) {
        File cache = new File(context.getApplicationContext().getCacheDir(), "picasso-cache");
        if (!cache.exists()) {
            //noinspection ResultOfMethodCallIgnored
            cache.mkdirs();
        }
        return cache;
    }

    public static long calculateDiskCacheSize(File dir) {
        long size = 5 * 1024 * 1024;
        try {
            StatFs statFs = new StatFs(dir.getAbsolutePath());
            long available = ((long) statFs.getBlockCount()) * statFs.getBlockSize();
            // Target 2% of the total space.
            size = available / 50;
        } catch (IllegalArgumentException ignored) {
        }
        // Bound inside min/max size for disk cache.
       return Math.max(Math.min(size, 50 * 1024 * 1024), 5 * 1024 * 1024);
    }
}
```
Afterwards i am using Picasso the following way:
```
Picasso.with(context).load(imageUrl).into(holder.coverImage);
```
I can't figure out what i am doing wrong but the images does not seem to be loaded from the disk cache. If i close the app and open it again the image is loaded from the network or the memory cache.

If i remove the downloader from the Picasso config then the cache works as expected.

Can anyone help me and tell me what i might be doing wrong?

**Comment by JakeWharton** [comment]
Everything looks fine. How are you determining that the cache isn't working?

**Comment by ChristianLJ** [comment]
Hi Jake,

I am using the indicators which always are green or red, but never yellow. 

The following scenario is also indicating that there's a problem.
When the phone is online and an image is loaded correctly, i can close the app, enable airplane mode and then open the app again, then the image is not loaded which i imagine it should be.

**Comment by JakeWharton** [comment]
Do the images have proper cache headers? Is the interceptor affecting their ability to be cached?

**Comment by ChristianLJ** [comment]
The images have the following response headers:
```
Access-Control-Allow-Methods:GET, POST, PUT, DELETE
Cache-Control:public, max-age=604800
Connection:Keep-Alive
Content-Encoding:gzip
Content-Type:text/html
Date:Sun, 01 Nov 2015 13:04:28 GMT
Expires:Sun, 08 Nov 2015 13:04:28 GMT
Keep-Alive:timeout=5, max=99
Server:Apache
Transfer-Encoding:chunked
Vary:Accept-Encoding
```
And the following request headers:
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,da;q=0.6,nb;q=0.4,de;q=0.2,it;q=0.2
Cache-Control:no-cache
Connection:keep-alive
Pragma:no-cache
```

The interceptor should not affect the ability to cache. The interceptors only responsibility is to check whether the request returns Unauthorized and if so fetch a new token and redo the request.

All of the image request URLs have the following structure:
```
https://url.com/productName/cover/ID.jpg?scale=540&quality=MED&access_token=ultralongtoken
```

The parameters of the URL changes over time, but does this affect the caching?

**Comment by ilyamuromets** [comment]
I have the same problem. Is there a solution?

**Comment by timolehto** [comment]
I'm having similar problems too.

**Comment by HolyPick** [comment]
Hi, I have exact the same problem.
I'm using: picasso in ver. 2.5.2 and okhttp ver. 2.7.2
Is there any solution for this problem ?

**Comment by shamo42** [comment]
I have the same problem with okhttp 2.7.5
@timolehto what version of okhttp are you using?

**Comment by liyyil** [comment]
I fixed it by switch from Picasso to UIL, as easy as Picasso and better performance...

**Comment by vickychijwani** [comment]
Hate to pile onto this thread, but this is still an issue with Picasso 2.5.2 + OkHttp 3.4.1. FWIW, here are my response headers:

```
Age: 287
Connection: keep-alive
Date: Sun, 09 Oct 2016 01:08:42 GMT
Etag: "e218d7b044e2df858e4e8983c8ae2655"
Server: AmazonS3
X-Cache: Hit from cloudfront
```

@shamo42's workaround of setting a custom cache also works for me.

**Comment by PingForward** [comment]
If some one still have this issue try to set cache for OkHttpClient
` builder.cache(new Cache(context.getCacheDir(), 25 * 1000 * 1000));`
and pass OkHttpClient to OkHttp3Downloader constructor
```
Picasso.Builder builder = new Picasso.Builder(context);
builder.downloader(new OkHttp3Downloader(client));
builder.memoryCache(new LruCache(context));
```

**Comment by prithivraj** [comment]
@JakeWharton 

This code is never caching the image. Am I missing something or is this a bug in Picasso?

```
val okHttpBuilder = OkHttpClient.Builder().addInterceptor { chain ->
                chain.proceed(chain.request())
            }
            val okHttpClient = okHttpBuilder.build()
            val picassoBuilder=Picasso.Builder(this);
            picassoBuilder.downloader(OkHttp3Downloader(okHttpClient))
            val picasso=picassoBuilder.build()
            picasso.setIndicatorsEnabled(true)
            picasso.isLoggingEnabled = true
            picasso.load("https://i.ytimg.com/vi/tRTFwzUH_ek/maxresdefault.jpg").into(image)
```
