### ISSUE TITLE
Wrong color codes for debug indicators in documentation

### ISSUE THREAD

**Issue by oliverhausler** [square/picasso#974]
I remember you changed color codes for debug indicators for the color-blind, but this change hasn't been reflected in your documentation here http://square.github.io/picasso/, and I can't find the new color codes anywhere.

Should be photoshopped in the image.

**Comment by JakeWharton** [comment]
I deployed the website which has the new colors.

**Comment by JakeWharton** [comment]
Good eye!

**Comment by oliverhausler** [comment]
@JakeWharton I am still seeing the old colors. Were we both talking about the same image and website?

http://square.github.io/picasso/static/debug.png

**Comment by JakeWharton** [comment]
Those are the new colors.

**Comment by hanbo** [comment]
The indicator colors on the website are still wrong. Using the current picasso version 2.5.2 i get red, blue, green. On the website is still red, yellow, green.
